### ISSUE TITLE
Doesn't work with keymaps

### ISSUE THREAD

**Issue by alexmozaidze** [yutkat/confirm-quit.nvim#1]
The prompt shows up when typing `:q` by hand, but with a keymap, it doesn't.
To reproduce, just try to quit with the following keymap:
```lua
vim.keymap.set("n", "<leader>q", "<cmd>q<cr>")
```

**Comment by yutkat** [comment]
The keymap quit is not supported at this time. I'll update later to support it.

**Comment by yutkat** [comment]
Supported this.

```lua
vim.keymap.set("n", "<leader>q", function() require("confirm-quit").confirm_quit() end)
```

https://github.com/yutkat/confirm-quit.nvim/commit/e9f32d44f2a7cab2711c25172310df87b48ea0e5

**Comment by alexmozaidze** [comment]
Thanks for the fix! Btw, you can pass the function directly to rhs since it doesn't take arguments like so:
```lua
vim.keymap.set("n", "<leader>q", require "confirm-quit".confirm_quit)
```
