### ISSUE TITLE
[Feature] Customize confirm prompt

### ISSUE THREAD

**Issue by FunctionalHacker** [yutkat/confirm-quit.nvim#10]
It would be nice to be able to customize the text in the confirm prompt, possible even the options but I would be happy with changing the "Do you want to quit?" text in the configuration.

**Comment by yutkat** [comment]
I agree. I modified it so that it can be changed.
https://github.com/yutkat/confirm-quit.nvim/commit/f15f6d728d385a3d2efa22098e9a45b8a2b20144

```lua
require("confirm-quit").setup({quit_message = "aaa"})
```
