### ISSUE TITLE
[Bug] Command substitution for `q` also works in search prompt

### ISSUE THREAD

**Issue by alexmozaidze** [yutkat/confirm-quit.nvim#2]
When I wanted to search with `/Alt q`, the `q` was being substituted by `lua require('confirm-quit').confirm_quit_cmdline()`.
I assume that it cannot distinguish between search and command mode.

Steps to reproduce:
1. Open search prompt with `/`
2. Type something that contains `q` (like `Alt q`)
3. See the bug appear as you hit space/enter

**Comment by yutkat** [comment]
Sorry. I used to be able to do it, but I made a mistake when I modified the logic recently.

I fixed it in this commit.
https://github.com/yutkat/confirm-quit.nvim/commit/05966ddffdaa96026264b218b5ed909afb2bc876
